services:
  comfyui:
    build: .
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./comfy_models:/home/comfyui/workspace/models
      - ./comfy_output:/home/comfyui/workspace/output
      - ./comfy_nodes:/home/comfyui/workspace/custom_nodes
      - ./comfy_user:/home/comfyui/workspace/user
      - ./.local:/home/comfyui/.local
      - ./.gemini:/home/comfyui/.gemini
      - ./script:/home/comfyui/script  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
